[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
local = "http://localhost:8545"
ddc="https://dev-exp-alpha.datadance.co/eth/rpc"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true